---
title: "R Plot"
output: html_notebook
---

https://stackoverflow.com/questions/45989198/how-to-load-all-fields-extendeddata-not-just-name-and-description-from-kml/51657844#51657844

#R Pakker og funksjoner


```{r setup}
library(sf)
library(tidyverse)
library(xml2)
library(rgdal)
#https://github.com/r-spatial/sf/issues/231
sfc_as_cols <- function(x, geometry, names = c("x","y")) {
  if (missing(geometry)) {
    geometry <- sf::st_geometry(x)
  } else {
    geometry <- rlang::eval_tidy(enquo(geometry), x)
  }
  stopifnot(inherits(x,"sf") && inherits(geometry,"sfc_POINT"))
  ret <- sf::st_coordinates(geometry)
  ret <- tibble::as_tibble(ret)
  stopifnot(length(names) == ncol(ret))
  x <- x[ , !names(x) %in% names]
  ret <- setNames(ret,names)
  dplyr::bind_cols(x,ret)
}


readKML <- function(file, keep_name_description = FALSE, layer, ...) {
  # Set keep_name_description = TRUE to keep "Name" and "Description" columns
  #   in the resulting SpatialPolygonsDataFrame. Only works when there is
  #   ExtendedData in the kml file.
  
  sp_obj <- rgdal::readOGR(file, layer, ...)
  xml1 <- read_xml(file)
  if (!missing(layer)) {
    different_layers <- xml_find_all(xml1, ".//d1:Folder")
    layer_names <- different_layers %>%
      xml_find_first(".//d1:name") %>%
      xml_contents() %>%
      xml_text()
    
    selected_layer <- layer_names == layer
    if (!any(selected_layer))
      stop("Layer does not exist.")
    xml2 <- different_layers[selected_layer]
  } else {
    xml2 <- xml1
  }
  
  # extract name and type of variables
  
  variable_names1 <-
    xml_find_first(xml2, ".//d1:ExtendedData") %>%
    xml_children()
  
  while (variable_names1 %>%
         xml_attr("name") %>%
         is.na() %>%
         any() & variable_names1 %>%
         xml_children() %>%
         length > 0)
    variable_names1 <- variable_names1 %>%
    xml_children()
  
  variable_names <- variable_names1 %>%
    xml_attr("name") %>%
    unique()
  
  # return sp_obj if no ExtendedData is present
  if (is.null(variable_names))
    return(sp_obj)
  
  data1 <- xml_find_all(xml2, ".//d1:ExtendedData") %>%
    xml_children()
  
  while (data1 %>%
         xml_children() %>%
         length > 0)
    data1 <- data1 %>%
    xml_children()
  
  data <- data1 %>%
    xml_text() %>%
    matrix(., ncol = length(variable_names), byrow = TRUE) %>%
    as.data.frame()
  
  colnames(data) <- variable_names
  
  if (keep_name_description) {
    sp_obj@data <- data
  } else {
    try(sp_obj@data <- cbind(sp_obj@data, data), silent = TRUE)
  }
  sp_obj
}

```


#Data
Laster inn data fra kml. Bruker funksjonen readKML for å få med tabellen i KML filen. I tillegg blir lokasjonen sorter i stigende rekkefølge og alle bestand some ikke er "ok" blir fjernet. 

```{r load}
#gran_org <- st_read("inn/Kartlegging av kortdistanse spredning fra bartrær.kml")
gran_org <- readKML("inn/Kartlegging av kortdistanse spredning fra bartrær.kml")
gran <- gran_org %>% st_as_sf %>% st_transform(25832)
gran <- sfc_as_cols(gran, st_centroid(geometry))
gran$Name <- as.numeric(as.character(gran$Name))
gran <- gran %>% arrange(Name)
gran <- gran %>% filter(Ok == 1)


```

#Ruter 500m
Ved å ta utgangspunkt i senterpunktet (x,y) regner man ut kordinatene til 500 meter kvadratene (x1-4,y1-4).  


https://stackoverflow.com/questions/44335246/polygons-from-coordinates
```{r 500meter}
plot500m <- gran %>% mutate(
  x1 = x + 250,
  y1 = y + 250,
  x2 = x - 250,
  y2 = y + 250,
  x3 = x + 250,
  y3 = y - 250,
  x4 = x - 250,
  y4 = y - 250,
)

plot500m$geometry <- NULL

df <- plot500m
lst <- lapply(1:nrow(df), function(x){
  ## create a matrix of coordinates that also 'close' the polygon
  res <- matrix(c(df[x, 'x1'], df[x, 'y1'],
                  df[x, 'x3'], df[x, 'y3'],
                  df[x, 'x4'], df[x, 'y4'],
                  df[x, 'x2'], df[x, 'y2'],
                  df[x, 'x1'], df[x, 'y1'])  ## need to close the polygon
                , ncol = 2, byrow = T
  )
  ## create polygon objects
  st_polygon(list(res))
  
})

## st_sfc : creates simple features collection
## st_sf : creates simple feature object
plot500meter <- st_sf(ID = df[, 'Name'], st_sfc(lst))
#df500meter <- cbind(df500meter, gran)
st_crs(df500meter) = 25832
```
#Ruter 2000m


```{r 2000meter}
plot2000m <- gran %>% mutate(
  x1 = x + 1000,
  y1 = y + 1000,
  x2 = x - 1000,
  y2 = y + 1000,
  x3 = x + 1000,
  y3 = y - 1000,
  x4 = x - 1000,
  y4 = y - 1000,
)

plot2000m$geometry <- NULL #Fjerner spatial data,

df <- plot2000m
lst <- lapply(1:nrow(df), function(x){
  ## create a matrix of coordinates that also 'close' the polygon
  res <- matrix(c(df[x, 'x1'], df[x, 'y1'],
                  df[x, 'x3'], df[x, 'y3'],
                  df[x, 'x4'], df[x, 'y4'],
                  df[x, 'x2'], df[x, 'y2'],
                  df[x, 'x1'], df[x, 'y1'])  ## need to close the polygon
                , ncol = 2, byrow = T
  )
  ## create polygon objects
  st_polygon(list(res))
  
})

## st_sfc : creates simple features collection
## st_sf : creates simple feature object
df2000meter <- st_sf(ID = df[, 'Name'], st_sfc(lst))
st_crs(df2000meter) = 25832
```

#Ut

Skriver resultatet til to filer.

```{r out}
df2000meter$Name <- as.character(df2000meter$ID)
df500meter$Name <- as.character(df500meter$ID)


st_write(df2000meter, delete_layer = TRUE , "out/plot2000meter_190823.shp")
st_write(df500meter, delete_layer = TRUE, "out/plot500meter.shp")

gran_out <- st_zm(gran, drop = TRUE, what = "ZM")
st_write(gran_out, delete_layer = TRUE, "out/senter.shp")
rm(df, plot500m, plot2000m, lst, gran_org, gran_out)


```



